# Generated by Django 6.0.6 on 2026-07-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', max_length=3)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fondy_order_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_invoice_pdf', models.FileField(blank=True, upload_to='payments/candidate_invoices/')),
                ('training_center_confirmation_pdf', models.FileField(blank=True, upload_to='payments/training_center_confirmations/')),
                ('partner_invoice_pdf', models.FileField(blank=True, upload_to='payments/partner_invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
