# Generated by Django 6.0.6 on 2026-08-18 07:33

import applications.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('seamans_book', "Seaman's Book"), ('certificate_of_competency', 'Certificate of Competency'), ('medical_certificate', 'Medical Certificate'), ('passport', 'Passport (ID page)'), ('other', 'Other document')], max_length=32)),
                ('file', models.FileField(upload_to=applications.models.application_document_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), applications.models.validate_document_size])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
