# Generated by Django 6.0.6 on 2026-07-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_country', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=64)),
                ('swift', models.CharField(max_length=32)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Training center',
                'verbose_name_plural': 'Training centers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('requirements', models.TextField(blank=True)),
                ('requirements_en', models.TextField(blank=True, null=True)),
                ('requirements_ru', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(max_length=255)),
                ('course_dates', models.TextField(blank=True, null=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('training_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.trainingcenter')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
