# Generated by Django 6.0.6 on 2026-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingcenter',
            name='fondy_receiver_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
