# Generated by Django 6.0.6 on 2026-08-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_trainingcenter_fondy_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
