# Generated by Django 6.0.6 on 2026-08-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('navigators', 'For Navigators'), ('engineers', 'For Engineers')], default='navigators', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
