# Generated by Django 6.0.6 on 2026-08-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_category_course_instructor_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(choices=[('navigation_bridge', 'Navigation & Bridge'), ('safety_compliance', 'Safety & Compliance'), ('cargo_operations', 'Cargo Operations'), ('ship_handling', 'Ship Handling'), ('regulations', 'Regulations'), ('environmental', 'Environmental')], default='navigation_bridge', max_length=24),
        ),
    ]
