# Generated by Django 6.0.6 on 2026-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='training_center_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
